app:
  build: .
  ports:
   - "80:3000"
  links:
   - mongo:mongo
   - game-creator:game-creator
  env_file: ./env/prod.sh

game-creator:
  build: ../game-creator/deployment
  links:
    - mongo:mongo

mongo:
  image: mongo:3.0.6
  links:
    - dbdata
  volumes_from:
    - dbdata

dbdata:
  image: cogniteev/echo
  volumes:
    - /var/lib/mongo/data/db:/data/db
