app:
  image: reminisceme/app
  ports:
   - "80:3000"
  links:
   - mongo:mongo
   - game-creator:game-creator
  env_file: ./env/prod.sh

mongo:
  image: mongo:3.0.6
  ports:
   - "27017:27017"
  volumes:
    - ./data/db:/data/db

game-creator:
  image: reminisceme/game-creator
  ports:
    - "9900:9900"
  links:
    - mongo:mongo
